### ISSUE TITLE
jsPerf Tests fail in IE10 & Firefox

### ISSUE THREAD

**Issue by EnzoMartin** [young-steveo/bitmask.js#1]

**Comment by young-steveo** [comment]
@EnzoMartin Did it stop failing? (I didn't change anything, lol.)

**Comment by EnzoMartin** [comment]
Nah going through and cleaning out my GitHub :P

Btw the RockGolem site is neat to see it's getting off the ground, though the links go to 404s (like the About page)

**Comment by young-steveo** [comment]
Yeah, I launched that yesterday and still haven't gone through the theme and updated everything.
